### ISSUE TITLE
插件加载失败，主页无法加载

### ISSUE THREAD

**Issue by FueGold** [AirboZH/plugin-uposs#6]
停用又拍云cdn后还原成域名访问博客后，之前设置的又拍云插件的附件管理-存储策略添加了新的存储策略，现在关闭了cdn使用域名访问网页会超时，请问如何关闭或禁用此插件，后台报错：2023-06-28T22:35:21.067+08:00  WARN 9756 --- [ ConnectionPool] okhttp3.OkHttpClient                     : A connection to https://v0.api.upyun.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by FueGold** [comment]
删除插件重启服务再重新登录后，弹出加载插件失败，再次重新登录可以成功，但是之前开启的插件，我删除插件后，再去删除附件-策略管理的oss后，无法删除，提示存在附件，但是，附件也无法删除，闭环了

**Comment by AirboZH** [comment]
又拍云现已支持S3协议，可以使用插件https://github.com/halo-sigs/plugin-s3
本插件/仓库不再提供支持

> 删除插件重启服务再重新登录后，弹出加载插件失败，再次重新登录可以成功，但是之前开启的插件，我删除插件后，再去删除附件-策略管理的oss后，无法删除，提示存在附件，但是，附件也无法删除，闭环了
